### ISSUE TITLE
Import Ratings from Letterboxd

### ISSUE THREAD

**Issue by UnknownUser6** [primetime43/Ratings-To-Plex-Ratings#4]
Not really an issue, since this program was not designed to do that, but is it possible to import ratings from a CSV file from Letterboxd? I tried to adjust the code, but unfortunately I can’t find a way to pair the Letterboxd links to an IMDb ID. I attached the CSV file I got from Letterboxd.

[letterboxd ratings.csv](https://github.com/primetime43/Ratings-To-Plex-Ratings/files/12216232/letterboxd.ratings.csv)

**Comment by primetime43** [comment]
> Not really an issue, since this program was not designed to do that, but is it possible to import ratings from a CSV file from Letterboxd? I tried to adjust the code, but unfortunately I can’t find a way to pair the Letterboxd links to an IMDb ID. I attached the CSV file I got from Letterboxd.
> 
> 
> 
> [letterboxd ratings.csv](https://github.com/primetime43/Ratings-To-Plex-Ratings/files/12216232/letterboxd.ratings.csv)
> 
> 

Sure, I'll look into adding support for letterboxd.

**Comment by primetime43** [comment]
Added Letterboxd support in v1.2 https://github.com/primetime43/Ratings-To-Plex-Ratings/releases/tag/1.2

**Comment by zdgro** [comment]
Hey! Thanks so much, this tool has been great and super simple to use. 
However when I imported my letterboxd scores it seemed to cut them in half, 5/5 movies are showing up 2.5/5. 
I assume this is because of the IMDB 10 star situation. If I had any coding experience I'm sure I could probably adjust it on my own but alas, I'm a dumbass. Is there any chance I might just be doing something wrong?
